# Generated by Django 5.2.7 on 2025-10-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
