# Generated by Django 5.2.7 on 2025-10-20 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_share_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share',
            old_name='created_by',
            new_name='user',
        ),
    ]
