# Generated by Django 5.2.7 on 2025-10-20 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_created_by_share_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share',
            old_name='user',
            new_name='creator',
        ),
    ]
