# Generated by Django 5.2.7 on 2025-10-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_share_participants_alter_share_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='currency',
            field=models.CharField(choices=[('USD', '$ USD 🇺🇸'), ('EUR', '€ EUR 🇪🇺'), ('GBP', '£ GBP 🇬🇧')], default='USD', max_length=100),
        ),
    ]
