# Generated by Django 5.2.7 on 2025-10-20 19:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_share_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='shares_participating', to=settings.AUTH_USER_MODEL),
        ),
    ]
