# Generated by Django 5.2.7 on 2025-10-20 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_share_participants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(verbose_name='Paid Date')),
                ('category', models.CharField(choices=[('activities', 'Activities 🏖️'), ('entertainment', 'Entertainment 🎟️'), ('food_drink', 'Food & Drink 🍽️'), ('housing', 'Housing 🏨'), ('shopping', 'Shopping 🛍️'), ('transportation', 'Transportation 🚗'), ('misc', 'Miscellaneous 💡')], default='activities', max_length=100)),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_by', to=settings.AUTH_USER_MODEL)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.share')),
                ('split_between', models.ManyToManyField(related_name='split_between', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
