# Generated by Django 5.2.7 on 2025-10-20 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_fare'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fare',
            options={'ordering': ['-date']},
        ),
    ]
